// Highlighted sidebar items
export const NEW = ['Color Bends', 'Ghost Cursor', 'Laser Flow', 'Liquid Ether', 'Pixel Blast', 'Floating Lines'];
export const UPDATED = [];

// Used for main sidebar navigation
export const CATEGORIES = [
  {
    name: 'Get Started',
    subcategories: ['Index']
  },
  {
    name: 'Text Animations',
    subcategories: [
      'Ascii Text',
      'Blur Text',
      'Circular Text',
      'Curved Loop',
      'Decrypted Text',
      'Falling Text',
      'Fuzzy Text',
      'Glitch Text',
      'Gradient Text',
      'Rotating Text',
      'Scroll Float',
      'Scroll Reveal',
      'Scroll Velocity',
      'Scramble Text',
      'Shiny Text',
      'Split Text',
      'Text Cursor',
      'Text Pressure',
      'Text Trail',
      'Text Type',
      'True Focus',
      'Variable Proximity',
    ],
  },
  {
    name: 'Animations',
    subcategories: [
      'Animated Content',
      'Blob Cursor',
      'Click Spark',
      'Count Up',
      'Crosshair',
      'Cubes',
      'Electric Border',
      'Fade Content',
      'Ghost Cursor',
      'Glare Hover',
      'Gradual Blur',
      'Laser Flow',
      'Logo Loop',
      'Magnet',
      'Magnet Lines',
      'Metallic Paint',
      'Noise',
      'Pixel Transition',
      'Ribbons',
      'Shape Blur',
      'Splash Cursor',
      'Star Border',
      'Sticker Peel',
      'Target Cursor',
    ],
  },
  {
    name: 'Components',
    subcategories: [
      'Animated List',
      'Bounce Cards',
      'Bubble Menu',
      'Card Nav',
      'Card Swap',
      'Carousel',
      'Chroma Grid',
      'Circular Gallery',
      'Counter',
      'Decay Card',
      'Dock',
      'Dome Gallery',
      'Elastic Slider',
      'Flowing Menu',
      'Flying Posters',
      'Folder',
      'Glass Icons',
      'Glass Surface',
      'Gooey Nav',
      'Infinite Menu',
      'Infinite Scroll',
      'Magic Bento',
      'Masonry',
      'Pixel Card',
      'Pill Nav',
      'Profile Card',
      'Rolling Gallery',
      'Scroll Stack',
      'Spotlight Card',
      'Stack',
      'Staggered Menu',
      'Stepper',
      'Tilted Card',
    ],
  },
  {
    name: 'Backgrounds',
    subcategories: [
      'Aurora',
      'Balatro',
      'Ballpit',
      'Beams',
      'Color Bends',
      'Dark Veil',
      'Dither',
      'Dot Grid',
      'Faulty Terminal',
      'Floating Lines',
      'Galaxy',
      'Gradient Blinds',
      'Grid Distortion',
      'Grid Motion',
      'Hyperspeed',
      'Iridescence',
      'Letter Glitch',
      'Lightning',
      'Light Rays',
      'Liquid Chrome',
      'Liquid Ether',
      'Orb',
      'Particles',
      'Pixel Blast',
      'Plasma',
      'Prism',
      'Prismatic Burst',
      'Ripple Grid',
      'Silk',
      'Squares',
      'Threads',
      'Waves',
    ],
  },
];
